apiVersion: v1
kind: Pod
metadata:
  name: "nginx-cm"
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
    - name: ENVIROMENT_TEST1
      valueFrom:
        configMapKeyRef:
          name: test-cm
          key: variable1
    - name: ENVIROMENT_TEST2
      valueFrom:
        configMapKeyRef:
          name: test-cm
          key: variable2

# kubectl create configmap test-cm --from-literal variable1=valor1 --from-literal variable2=valor2
# kubectl get cm
# kubectl get cm -oyaml test-cm
# kubectl describe cm test-cm
# kubectl delete cm test-cm

# kubectl apply -f cm-pod.yml
# kubectl delete -f cm-pod.yml
# kubectl get all
# kubectl exec -it nginx-cm bash
  # env