apiVersion: v1
kind: Pod
metadata:
  name: cmpod
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
    - name: ENVIROMENT_TEST1
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: variable1
    - name: ENVIROMENT_TEST2
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: variable2

# kubectl apply -f cm-pod.yml
# kubectl delete -f cm-pod.yml
# kubectl get all
# kubectl exec -it cmpod bash
  # env