apiVersion: v1
kind: Pod
metadata:
  name: cmpod
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
    envFrom:
        - configMapRef:
            name: myconfigmap
# kubectl apply -f cm-pod.yml
# kubectl delete -f cm-pod.yml
# kubectl get all
# kubectl exec -it cmpod bash
  # env