apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: default
data:
  variable1: value1
  variable2: value2

# kubectl apply -f ConfigMap.yml
# kubectl describe cm myconfigmap
# kubectl delete -f ConfigMap.yml
# kubectl get cm