apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-volume-claim
  namespace: default
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-volume-claim-1
  containers:
    - name: pv-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-storage

# kubectl get pods
# kubectl apply -f pv-pod-volume-claim.yml
# kubectl describe pod pv-pod-volume-claim
# kubectl exec -it pv-pod-volume-claim bash
  # mount |grep /usr/share/nginx/html
  # echo hola > index.html
  # ls
  # touch /testfile
  # ls /testfile
  # exit
# kubectl delete -f pv-pod-volume-claim.yml