apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-001
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv-volume-001"

# kubectl get pv
# kubectl apply -f pv-volume-001.yml
# kubectl describe pv pv-volume-001
# kubectl delete -f pv-volume-001.yml