apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
    matchExpressions:
      - {key: environment, operator: In, values: [testing]}
  template:
    metadata:
      labels:
        app: nginx
        environment: testing
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort:  80
# kubectl apply -f ReplicaSet.yml
# kubectl delete -f ReplicaSet.yml
# kubectl get all