apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller
spec:
  replicas: 2
  selector: # Etiquetas del ReplicationController
    project: nginx # Nombre: Valor
    environment: testing
  template:
    metadata:
      name: nginx
      labels:
        project: nginx
        environment: testing
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
# kubectl apply -f ReplicationController.yml
# kubectl delete -f ReplicationController.yml
# kubectl get all
# kubectl get all -o wide