apiVersion: v1
kind: Service
metadata:
  name: service-cluster-ip
  namespace: default
spec:
  type: ClusterIP # Solo accesible dentro del cluster
  selector: # redirecciona el trfico a cualquier pod q cumpla con las etiquetas
    app: nginx
    environment: testing
  ports:
  - protocol: TCP
    port: 8080 # Puerto al cual se le deben hacer las peticiones al cluster
    targetPort: 80 # puerto al que redireccionna internamente el tráfico
    
# kubectl apply -f ServiceClusterIP.yml
# kubectl delete -f ServiceClusterIP.yml
# kubectl get all

# kubectl get pods -o wide
# kubectl exec -it pod/replica-set-[RANDOM] bash [Para entrar al bash dentro del pod]
# curl [IP-POD]:8080
# curl service-cluster-ip:8080

# kubectl get nodes
# minikube ssh
# curl [IP-CLUSTER]:8080

# kubectl describe service service-cluster-ip